# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('imei', models.CharField(max_length=15)),
                ('s_str', models.CharField(blank=True, max_length=10, null=True)),
                ('dev_time', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('humidity', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersImei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_numbers', models.CharField(max_length=15)),
                ('device_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersimei',
            unique_together=set([('imei_numbers', 'device_name', 'user')]),
        ),
    ]
