# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170228_1013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersimei',
            unique_together=set([]),
        ),
    ]
